### ISSUE TITLE
Minifying filter defs in inline SVG

### ISSUE THREAD

**Issue by sciloqi** [hexydec/htmldoc#11]
I have some issues with filters and encapsulated tags in the SVG defs section (inline) while minifying:

```html
<svg width="100%" height="100%" viewBox="0 0 460 340" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <filter id="drop-shadow-filter-0" color-interpolation-filters="sRGB" x="-500%" y="-500%" width="1000%" height="1000%">
      ...
      <feComponentTransfer result="offsetblur" in="offset-0">
        <feFuncA id="spread-ctrl" type="linear" slope="1.32"/>
      </feComponentTransfer>
      ...
```

results in

```html
<svg width="100%" height="100%" viewBox="0 0 460 340" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <filter id="drop-shadow-filter-0" color-interpolation-filters="sRGB" x="-500%" y="-500%" width="1000%" height="1000%">
      ...
      <feComponentTransfer result="offsetblur" in="offset-0"></feComponentTransfer>
      <feFuncA id="spread-ctrl" type="linear" slope="1.32"></feFuncA>
      ...
```

closing `<feComponentTransfer>` to early and bringing `<feFunc>` one level up. None of the options made a difference...

Happy Holidays 🎄

**Comment by hexydec** [comment]
Hey, thanks for letting me know about this and providing an example, looks like the `feComponentTransfer` element was incorrectly listed as a singleton.

Have removed from the list and should now work correctly.

Happy holidays to you too.

**Comment by sciloqi** [comment]
Great, thank you! 

The same goes for `feMerge`. I removed it from the configuration like you did with `feComponentTransfer` and now I can see all my filters again...!

**Comment by hexydec** [comment]
Have checked over the whole list now, also removed `feDiffuseLighting`.

Let me know if any more issues.
