### ISSUE TITLE
FatalError

### ISSUE THREAD

**Issue by robiul215** [hexydec/htmldoc#6]
here is the error for laravel please check.
"Declaration of hexydec\html\htmldoc::offsetGet(hexydec\html\mixed $i): hexydec\html\mixed must be compatible with ArrayAccess::offsetGet($offset)"
https://prnt.sc/ZoRL9tt6K9_j

**Comment by hexydec** [comment]
What version of PHP are you using?

**Comment by hexydec** [comment]
Looking at the error your static analyser is generating, you must be using PHP 7.4. The issue is that the type hint `mixed` was not introduced until PHP 8.

I have fixed the regression now, please update your build to use[ v1.7.0](https://github.com/hexydec/htmldoc/releases/tag/1.7.0).

**Comment by robiul215** [comment]
Yeah, It's Work Now :)
thanks for update
