### ISSUE TITLE
HTML5 parsing and serialization in PHP 8.4

### ISSUE THREAD

**Issue by jensscherbl** [hexydec/htmldoc#9]
Not sure if this is relevant for htmldoc, just wanted to put it on your radar as well.

https://wiki.php.net/rfc/domdocument_html5_parser

**Comment by hexydec** [comment]
I did tryout `DOMDocument` before writing this, and found it unsuitable for the reasons specified in the RFC.

Would be a complete rewrite if it does land, so we'll have to see!

**Comment by jensscherbl** [comment]
@hexydec Has landed ;)

https://www.php.net/releases/8.4/en.php#dom_additions_html5

Let me know if I can help with anything, would be an interesting project.

**Comment by hexydec** [comment]
Thanks for the heads up. Will have a think about how it might work.

**Comment by jensscherbl** [comment]
@hexydec Just came across two interesting articles in this context from someone who maintains a PHP port of Mozilla’s Readability. One is an interview with the guy who implemented this in PHP 8.4.

- https://blog.keyvan.net/p/parsing-html-with-php-84
- https://blog.keyvan.net/p/interview-with-niels-dossche

From my understanding, the new native implementation already takes care of parsing and querying, so HTMLdoc could probably adopt these parts and focus more on optimization and minification going forward.
